# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/RecursiveG/Mc122477Fix/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
license="MIT"
[[mods]] #mandatory
# The modid of the mod
modId="mc122477fix" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="MC-122477 Fix" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/RecursiveG/Mc122477Fix" #optional
# A text field displayed in the mod UI
authors="RecursiveG" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Fix MC-122477, which causes double-typing 't' or '/' on Linux.
'''
